export const ADD_SCHEDULE = 'ADD_SCHEDULE'
export const SORT_SCHEDULE = 'SORT_SCHEDULE'
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE'
export const DELETE_ALL_SCHEDULS = 'DELETE_ALL_SCHEDULS'
export const ISOPEN_TOGGLE = 'ISOPEN_TOGGLE'

