export const ADD_SCHEDULE = 'ADD_SCHEDULE'
export const SORT_SCHEDULE = 'SORT_SCHEDULE'
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE'
export const DELETE_ALL_SCHEDULS = 'DELETE_ALL_SCHEDULS'
export const HANDLE_OPEN = 'HANDLE_OPEN'
export const HANDLE_CLOSE = 'HANDLE_CLOSE'


